site_name: ' DITA and MkDocs'

markdown_extensions:
    - pymdownx.snippets:

nav:
-  Home: index.md
-  'Initial set-up':
     -  'Installing Python': 'en/ta_installing_python.md'
     -  'Creating a new MkDocs project': 'en/ta_creating_a_mkdocs_project.md'
     -  'Installing the ReadTheDocs DITA-ot plug-in': 'en/ta_installint_the_readthedocs_dita_ot_plug_in.md'
-  'Tips and Tricks':
     -  'Tips and tips when using the ReadtheDocs DITA-OT plug-in': 'en/co_tips_and_tips_when_using_the_readthedocs_dita_ot_plug_in.md'
-  'Publication':
     -  'Creating a ReadtheDocs transformation scenario in OxygenXML': 'en/ta_publishing_a_readthedocs_project_in_oxygenxml.md'
     -  'Creating the necessary files for the MkDocs projects': 'en/ta_adding_your_generated_markdown_topics_to_the_mkdocs_projects.md'
     -  'Checking your MkDocs project in a local environment': 'en/ta_checking_your_mkdocs_project_on_a_localhost.md'
-  'Troubleshooting':
     -  'Link to media files is broken': 'en/tr_link_to_media_files_is_wrong.md'

theme: mkdocs