[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "OxygenXML"
authors = [{name = "Pieterjan Vandenweghe", email = "pieterjan.vandenweghe@flowtime.be"}]
dynamic = ["version", "description"]
