site_name: ' OxygenXML'


pages:
-  Home: index.md
 -  'Guidelines for writing in Oxygen XML': 'en/to_guidelines_and_tips_oxygen_xml.md'
 -  'Guidelines for chunking content': 'en/re_guidelines_writing_topics.md'
 -  'Guidelines for writing topic titles': 'en/re_guidelines_writing_topic_titles.md'
 -  'Guidelines for file naming': 'en/re_guidelines_file_naming_topics.md'
 -  'Guidelines for using sections': 'en/re_guidelines_sections.md'
 -  'Guidelines for creating DITA maps and bookmaps': 'en/re_guidelines_ditamaps.md'
 -  'Guidelines for working with graphics': 'en/re_guidelines_images.md'
 -  'Guidelines for creating links': 'en/re_guidelines_creating_links.md'
 -  'Guidelines for using content references': 'en/re_guidelines_content_reference.md'
 -  'Guidelines for conditional processing': 'en/re_guidelines_conditional_processing.md'
 -  'Tips for writing in Oxygen XML': 'en/to_tips_oxygen.md'
 -  'Changing the style of topics': 'en/to_changing_style_topic.md#to_changing_style_topic'
 -  'To hide the keyref attribute to make xrefs better legible': 'en/to_changing_style_topic.md#task_uc2_js2_rmb'
 -  'Changing the style of ditamaps': 'en/to_changing_style_ditamap.md#to_changing_style_ditamap'
 -  'To display topic titles instead of file names': 'en/to_changing_style_ditamap.md#ta_displaying_topic_titles_instead_of_file_names_in_a__ditamap_file'
 -  'To edit topicref attributes in place': 'en/to_changing_style_ditamap.md#ta_display_attributes_in_map'
 -  'Adding images and videos': 'en/to_adding_images_videos.md'
 -  'To add images to the Reusable Components pane': 'en/ta_adding_images_dita_reusable_components.md'
 -  'To insert images using the Reusable Components pane': 'en/ta_using_reusable_components.md'
 -  'To embed a YouTube video in a DITA topic': 'en/ta_embedding_a_youtube_video_in_dita.md'
 -  'Adding glossaries through tooltips': 'en/to_glossaries_through_tooltips.md'
 -  'What are tooltips?': 'en/co_glossaries_versus_tooltips.md'
 -  'To create a glossary': 'en/ta_creating_a_glossary.md'
 -  'To add a tooltip for Oxygen's online help output': 'en/ta_reference_the_glossary_term_in_a_topic.md'
 -  'Adding additional components to a ditamap': 'en/to_adding_elements_ditamap.md#to_adding_elements_ditamap'
 -  'To add non-DITA content to a DITA map': 'en/to_adding_elements_ditamap.md#taskId12'
 -  'To add a key with keyword to a DITA map': 'en/to_adding_elements_ditamap.md#ta_adding_a_key_to_a_ditamap_file'
 -  'Creating transformation scenarios': 'en/to_creating_transformation_scenarios.md#to_creating_transformation_scenarios'
 -  'To select a custom DITA-OT in Oxygen XML': 'en/to_creating_transformation_scenarios.md#ta_selecting_a_custom_dita_ot_in_oxygenxml'
 -  'To group transformations scenarios': 'en/to_creating_transformation_scenarios.md#ta_grouping_transformations_in_the_configure_transformation_scenario_s_view'
 -  'Searching and replacing': 'en/to_searching_replacing.md#to_searching_replacing'
 -  'To use the find replace function': 'en/to_searching_replacing.md#ta_find_replace'
 -  'To add refactoring operations to the Oxygen XML editor': 'en/to_searching_replacing.md#adding_refactoring_script_to_the_oxygen_project'
 -  'Adding spell checks': 'en/to_dictionary.md#to_dictionary'
 -  'To add a Dutch dictionary to Oxygen's Spell Check': 'en/to_dictionary.md#ta_adding_a_dutch_dictionary_to_oxygen_s_spell_check'
 -  'Publishing DITA content in Oxygen XML': 'en/to_publishing_dita_content.md#to_publishing_dita_content'
 -  'To select a custom DITA-OT in Oxygen XML': 'en/to_publishing_dita_content.md#ta_selecting_a_custom_dita_ot_in_oxygenxml'
 -  'To create a transformation scenario': 'en/to_publishing_dita_content.md#ta_create_webhelp_transformation'
 -  'To import a transformation scenario': 'en/to_publishing_dita_content.md#ta_importing_a_transformation_scenario'
 -  'To export a transformation scenario': 'en/to_publishing_dita_content.md#ta_exporting_a_transformation_scenario'
 -  'To publish DITA content with DITA-OT': 'en/to_publishing_dita_content.md#ta_publishing_your_dita_content_to_multiple_output_formats'
 -  'To publish a single topic with resolved \(con\)keyref': 'en/to_publishing_dita_content.md#ta_to_publish_a_single_topic_with_resolved_con_keyref'
 -  'Detecting and fixing style guide errors in Oxygen XML': 'en/co_validation_checks_in_oxygenxml.md'
 -  'To add a validation check to your custom framework': 'en/ta_adding_a_validation_check_to_your_custom_framework.md'
 -  'To configure a validation scenario': 'en/ta_configuring_a_validation_scenario.md'
 -  'To run a validation scenario': 'en/ta_running_a_validation_scenario.md'
 -  'Oxygen XML troubleshooting': 'en/to_oxygen_xml_troubleshooting.md#oxygen_xml_troubleshooting'
 -  'Oxygen XML takes long to start': 'en/to_oxygen_xml_troubleshooting.md#tr_application_takes_long_to_start'
theme: readthedocs